### PR TITLE
Rename `querystring` `urlencode`/`urldecode`

### PR DESCRIPTION
**Pull request by RiskoZS**

### CODE REVIEW

**Comment by truemedian** [comment]
`encodeString` and `decodeString` is not an accurate representation of what is happening here given its placement in the querystring library.

I would actually like to pull both of these functions out of here and place them in `uri`, where they actually belong.

**Comment by RiskoZS** [comment]
Won't that create a cyclic dependency between `uri` (which I assume was Luvit's `url`) and `querystring`?

**Comment by truemedian** [comment]
Yes it would, which is why I didn't do it initially. It might be worth removing parse_querystring from uri.decode and expecting the user to parse the querystring themselves if they need it.

One thing to note is that [RFC 3986 Section 3.4](https://datatracker.ietf.org/doc/html/rfc3986#section-3.4), only states that `key=value` is **common**, technically any valid string can be placed in the query component

**Comment by truemedian** [comment]
This has been fixed in d53b11427cdd9d37d0910e28df49f9c4d2442179, and parse_querystring has been removed on uri.decode

**Pull request closed without merging**
